#!/bin/bash

CGO_ENABLED=0 go build -ldflags '-extldflags "-static"' server.go

acbuild begin
acbuild set-name example.com/server
acbuild copy server /bin/server
acbuild set-exec /bin/server
acbuild port add www tcp 5000
acbuild label add version 0.0.1
acbuild label add arch amd64
acbuild label add os linux
acbuild annotation add authors "Alexandru Topliceanu <alexandru@pusher.com>"
acbuild write server-0.0.1-linux-amd64.aci
acbuild end
