# A sample Gemfile
source "https://rubygems.org"

# Version of ruby used.
ruby "2.2.3"

# Required gems.
gem "pry", "0.10.2"
gem "sinatra", "1.4.6"
gem "thin", "1.6.4"
gem "redis", "3.2.1"
gem "em-websocket", "0.5.1"
gem "em-hiredis", "0.3.0"
gem "foreman", "0.78.0"
gem "juggler", "0.1.0"
