---
# Modified from https://github.com/microservices-demo/microservices-demo
# Please see this repository for the original

apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    name: shipping
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: shipping

